### PR TITLE
Update personal_contributor_licence_agreement.md

### PR DESCRIPTION
**Pull request by 9t8**

### CODE REVIEW

**Comment by brackets-io** [comment]
Line Format Error: The expected line should be: | `full name` | [git-username](https://github.com/git-username) | dd-month-yyyy | 

Date Error: The expected line should be: | `full name` | [git-username](https://github.com/git-username) | dd-month-yyyy | 
Invalid date: Date should be within one week of <today's date in dd-month-YYYY format>
Error: 9t8 has already signed the personal contributor license agreement.

**Comment by abose** [comment]
Hi @9t8, Thanks for signing the CLS. There appears to be an error:
Please change to:
`| David L | [9t8](https://github.com/9t8) | 10 January 2023 |`

instead of 

`David L | [9t8](https://github.com/9t8) | 10 January 2023`

**Comment by brackets-io** [comment]
## Error: The pull request should have only a single commit. 
        Please squash all your commits and update this pull request.
        more help: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
        
Line Format Error: The expected line should be: | `full name` | [git-username](https://github.com/git-username) | dd-month-yyyy | 

Date Error: The expected line should be: | `full name` | [git-username](https://github.com/git-username) | dd-month-yyyy | 
Invalid date: Date should be within one week of <today's date in dd-month-YYYY format>
Error: 9t8 has already signed the personal contributor license agreement.

**Comment by abose** [comment]
Hi @9t8, The checks fail as quotes are missing from the name. sorry for missing that in the earlier exaple.

```md
| `David L` | [9t8](https://github.com/9t8) | 10 January 2023 |

notice the ` in | `David L` |
```

**Comment by brackets-io** [comment]
## Error: The pull request should have only a single commit. 
        Please squash all your commits and update this pull request.
        more help: https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git
        
Line Format Error: The expected line should be: | `full name` | [git-username](https://github.com/git-username) | dd-month-yyyy | 

Date Error: The expected line should be: | `full name` | [git-username](https://github.com/git-username) | dd-month-yyyy | 
Invalid date: Date should be within one week of <today's date in dd-month-YYYY format>
Error: 9t8 has already signed the personal contributor license agreement.

**Comment by abose** [comment]
Thanks, @9t8 for signing the CLA and helping with brackets development.

**Pull request merged**
